
all:
  children:
    masters:
      hosts:
        k8s-master1:
          ansible_host: 10.1.46.128
        k8s-master2:
          ansible_host: 10.1.46.197
        k8s-master3:
          ansible_host: 10.1.46.127

    workers:
      hosts:
        k8s-worker1:
          ansible_host: 10.1.46.195
        k8s-worker2:
          ansible_host: 10.1.46.196

lb: 
  children:
    masters-lb: 
      hosts: 
        k8s-masters-lb1: 
          ansible_host: 10.1.46.128
        k8s-masters-lb2:
          ansible_host: 10.1.46.127
