
all:
  children:
    workers:
      hosts:
        worker1:
          ansible_host: 172.25.51.35
        worker2:
          ansible_host: 172.25.51.53
        worker3:
          ansible_host: 172.25.51.46
        worker4:
          ansible_host: 172.25.51.31
        worker5:
          ansible_host: 172.25.51.14
        worker6:
          ansible_host: 172.25.51.47
        
        

