
all:
  children:
    masters:
      hosts:
        k8s-master1:
          ansible_host: 192.168.20.141
        k8s-master2:
          ansible_host: 192.168.20.143
        k8s-master3:
          ansible_host: 192.168.20.146

    # workers:~
    #   hosts:
    #     k8s-worker1:
    #       ansible_host: 192.168.56.21
    #     k8s-worker2:
    #       ansible_host: 192.168.56.22

lb: 
  children:
    masters-lb: 
      hosts: 
        k8s-masters-lb: 
          ansible_host: 192.168.20.149
