# -------------------------------
# HANDLERS
# -------------------------------
- name: Set NiFi permissions
  ansible.builtin.file:
    path: "{{ nifi_install_dir }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    recurse: yes
