---
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#]\S+)\s+\S+\s+swap\s+'
    replace: '# \1 swap disabled'

- name: Enable kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load kernel modules
  command: modprobe {{ item }}
  with_items:
  - overlay
  - br_netfilter

- name: Configure sysctl
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl params
  command: sysctl --system

- name: Configure Kubernetes repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl={{ k8s_repo_baseurl }}
      enabled=1
      gpgcheck=1
      gpgkey={{ k8s_repo_gpgkey }}
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Install Kubernetes packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started
