nifi_version: 2.6.0
nifi_user: nifi
nifi_group: nifi
nifi_install_dir: /data/nifi
nifi_data_dir: /data/nifi
nifi_download_url: "https://dlcdn.apache.org/nifi/2.6.0/nifi-2.6.0-bin.zip"

# Cluster settings
nifi_nodes:
  - nifi01:10.1.80.111
  - nifi02:10.1.80.112
  - nifi03:10.1.80.113

nifi_web_port: 8080
nifi_cluster_port: 8081