# stop disable firewall 
- name: Stop and disable firewalld
  hosts: 
  - nifi
  become: true
  tasks:
  - name: Stop firewalld service
    service:
      name: firewalld
      state: stopped
      enabled: no